# Generated by Django 5.0.4 on 2024-04-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=100)),
                ('instructions', models.CharField(max_length=100)),
                ('preparation_time', models.CharField(max_length=100)),
                ('cooking_time', models.CharField(max_length=100)),
                ('total_time', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], max_length=100)),
                ('nutrition_information', models.CharField(max_length=100)),
                ('recipe_image', models.ImageField(upload_to='media')),
                ('category', models.CharField(choices=[('breakfast', 'breakfast'), ('launch', 'launch'), ('dinner', 'dinner')], max_length=100)),
                ('tags', models.CharField(choices=[('vegetarian', 'vegetarian'), ('non_vegetarian', 'non_vegetarian')], max_length=100)),
                ('total_calorie', models.CharField(max_length=100)),
            ],
        ),
    ]
