# Generated by Django 5.0.4 on 2024-04-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_recipemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='category',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner')], max_length=100),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='difficulty_level',
            field=models.CharField(choices=[('hard', 'hard'), ('medium', 'medium'), ('easy', 'easy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='tags',
            field=models.CharField(choices=[('vegetarian', 'vegetarian'), ('vegan', 'vegan')], max_length=100),
        ),
    ]
