# Generated by Django 5.0.3 on 2024-04-29 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0005_chefmodel_viewermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefmodel',
            name='experience',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chefmodel',
            name='myuser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chefmodel',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='chefmodel',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='chefmodel',
            name='skill',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='viewermodel',
            name='favourite',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='viewermodel',
            name='myuser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viewermodel',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
